### PR TITLE
review changes 

### PR DESCRIPTION
**Pull request by bgruening**
this PR does:

* merge master
* fix metadata so that the first slides are now generated correctly
* fix spelling
* add more links and references
* fix some ugly footnotes
* add some keypoints to the architecture sildes

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton if you agree and merge this I will merge your PR so we have everything in master and can improve it on master.

**Comment by jmchilton** [comment]
That is a lot of commits :)

**Comment by jmchilton** [comment]
Oh - I see that was master it was merged with - makes sense now.

**Comment by bgruening** [comment]
My changes are all in the last commit ...

**Pull request merged**
